Controllers/NotaFiscalsController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Xml.Linq;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using projFront.Data;
using projFront.Models;
using projFront.Repository;
using projFront.Services;
using projFront.ViewModels;
using Rotativa.AspNetCore;

namespace projFront.Controllers
{
    [Authorize(Roles = "Admin, Operador")]
    public class NotaFiscalsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly INotaFiscalServices _notaFiscalServices;
        private readonly IEmpresaServices _empresaServices;
        private readonly IBancoServices _bancoServices;
        private readonly IMapper _mapper;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public NotaFiscalsController(AppDbContext context, INotaFiscalServices notaFiscalServices, IMapper mapper, IEmpresaServices empresaServices, IBancoServices bancoServices, IHttpContextAccessor httpContextAccessor, UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _notaFiscalServices = notaFiscalServices;
            _mapper = mapper;
            _empresaServices = empresaServices;
            _bancoServices = bancoServices;
            _httpContextAccessor = httpContextAccessor;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        // GET: NotaFiscals
        public async Task<IActionResult> Index()
        {
            ViewData["PaginaSelecionada"] = "NotaFiscal";
            ViewData["DireitoUsuario"] = IdentificaDireitoUsuario();

            List<NotaFiscalViewModel> listaNotaFiscalViewModel = new List<NotaFiscalViewModel>();
            //_notaFiscalServices.RetornaListaNotaFiscal()

            if (_context.Empresas != null)
            {
                // Obter lista de NotaFiscal
                List<NotaFiscal> listaNotaFiscal = await _context.NotaFiscal.ToListAsync();

                // Mapear para a ViewModel
                //listaNotaFiscalViewModel = _mapper.Map<IEnumerable<NotaFiscalViewModel>>(listaNotaFiscal);

                foreach (var nota in listaNotaFiscal)
                {
                    var nfVm = transformaNotaficalVM(nota);
                    listaNotaFiscalViewModel.Add(nfVm);
                }

                // Criar um dicionário para mapear o ID da NotaFiscal para a inscrição estadual
                var inscricaoEstadualMap = listaNotaFiscal.ToDictionary(nf => nf.Id, nf => nf.IncricaoEstadual);

                // Atribuir a inscrição estadual utilizando o dicionário
                foreach (var nfViewModel in listaNotaFiscalViewModel)
                {
                    if (inscricaoEstadualMap.TryGetValue(nfViewModel.Id, out var inscricaoEstadual))
                    {
                        nfViewModel.Ie = inscricaoEstadual;
                    }
                }
            }

            var usuarioLogado = _httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            List<Empresa> listEmpresa = _empresaServices.GetEmpresas();

            List<Banco> listaBanco =  _bancoServices.ListaBancosPorUsuario(usuarioLogado);

            List<NotaFiscalViewModel> listaFiltrada = new List<NotaFiscalViewModel>();

            foreach (var notas in listaNotaFiscalViewModel)
            {
                int idEmpresaRelacionada = int.Parse(notas.IdEmpresa);
                Empresa empresa = listEmpresa.FirstOrDefault(x => x.IdEmpresa == idEmpresaRelacionada);
                notas.Empresa = new List<Empresa>();
                notas.Empresa.Add(empresa);
                foreach (var bancosDoUsuario in listaBanco)
                {

                    if(bancosDoUsuario.IdBanco == notas.IdBanco)
                        listaFiltrada.Add(notas);
                }
            }

            return View(listaFiltrada);
        }

        // GET: NotaFiscals/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            ViewData["PaginaSelecionada"] = "NotaFiscal";
            ViewData["DireitoUsuario"] = IdentificaDireitoUsuario();
            if (id == null || _context.NotaFiscal == null)
            {
                return NotFound();
            }

            var notaFiscal = await _context.NotaFiscal
                .FirstOrDefaultAsync(m => m.Id == id);
            if (notaFiscal == null)
            {
                return NotFound();
            }
            NotaFiscalViewModel notaFiscalVM = _mapper.Map<NotaFiscalViewModel>(notaFiscal);
            return View(notaFiscalVM);
        }

        // GET: NotaFiscals/Create
        public IActionResult Create()
        {
            ViewData["PaginaSelecionada"] = "NotaFiscal";
            ViewData["DireitoUsuario"] = IdentificaDireitoUsuario();

            List<Empresa> listEmpresa = new List<Empresa>();

            listEmpresa = _empresaServices.GetEmpresas();

            NotaFiscalViewModel notaFiscalViewModel = new NotaFiscalViewModel();

            notaFiscalViewModel.Empresa = listEmpresa;

            List<Banco> listBanco = new List<Banco>();

            var usuarioLogado = _httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            listBanco =_bancoServices.ListaBancosPorUsuario(usuarioLogado);

            notaFiscalViewModel.Banco = listBanco;

            return View(notaFiscalViewModel);
        }

        // POST: NotaFiscals/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( NotaFiscalViewModel notaFiscalVM)
        {
            ViewData["PaginaSelecionada"] = "NotaFiscal";
            ViewData["DireitoUsuario"] = IdentificaDireitoUsuario();
            notaFiscalVM.Empresa = _empresaServices.GetEmpresa(Convert.ToInt32(notaFiscalVM.IdEmpresa));
            notaFiscalVM.MensagemFisco = notaFiscalVM.Empresa[0].MensagemFisco;
            notaFiscalVM.Banco   = _bancoServices.GetBanco(notaFiscalVM.IdBanco);
            notaFiscalVM.UserName = _httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.Name).Value;

            NotaFiscal notaFiscal = transformaNotafical(notaFiscalVM);
               
            _context.Add(notaFiscal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            
        }

        private NotaFiscal transformaNotafical(NotaFiscalViewModel notaFiscalVM)
        {
            NotaFiscal notaFiscal = new NotaFiscal();
            notaFiscal.Id = notaFiscalVM.Id;
            notaFiscal.Nome = notaFiscalVM.Nome;
            notaFiscal.Cnpj = notaFiscalVM.Cnpj;
            notaFiscal.IncricaoEstadual = notaFiscalVM.Ie == null ? "" : notaFiscalVM.Ie;
            notaFiscal.Endereco = notaFiscalVM.Endereco;
            notaFiscal.Numero = notaFiscalVM.Numero;
            notaFiscal.Bairro = notaFiscalVM.Bairro;
            notaFiscal.NomeCidade = notaFiscalVM.NomeCidade;
            notaFiscal.Uf = notaFiscalVM.Uf;
            notaFiscal.Cep = notaFiscalVM.Cep;
            notaFiscal.NumeroTelefone = notaFiscalVM.NumeroTelefone == null ? "" : notaFiscalVM.NumeroTelefone;
            notaFiscal.DescricaoServico = notaFiscalVM.DescricaoServico;
			CultureInfo culturaBrasileira = new CultureInfo("pt-BR");
            decimal valorDecimal = 0;

            if (notaFiscalVM.ValorTotal.Contains(","))
            {
                notaFiscalVM.ValorTotal = notaFiscalVM.ValorTotal.Replace(",", ".");
            }

            if (!notaFiscalVM.ValorTotal.Contains("."))
            {
                notaFiscalVM.ValorTotal = notaFiscalVM.ValorTotal + ".00";
            }

            if (decimal.TryParse(notaFiscalVM.ValorTotal, NumberStyles.Any, CultureInfo.InvariantCulture, out valorDecimal))
			{
				Console.WriteLine("Valor decimal: " + valorDecimal); // Imprimirá 180.85
			}
			else
			{
				Console.WriteLine("Falha na conversão.");
			}
			notaFiscal.ValorTotal = Math.Round(valorDecimal, 2);
            notaFiscal.IdBanco = notaFiscalVM.IdBanco;
            notaFiscal.Agencia = notaFiscalVM.Banco[0].Agencia;
            notaFiscal.Conta = notaFiscalVM.Banco[0].TipoConta;
            notaFiscal.PixChave = notaFiscalVM.Banco[0].PixChave;
            notaFiscal.PixNumero = notaFiscalVM.Banco[0].PixNumero;
            notaFiscal.IdEmpresa = Convert.ToInt32( notaFiscalVM.IdEmpresa);
            notaFiscal.DataEmissao = notaFiscalVM.DataEmissao;
            notaFiscal.FaturaSerie = notaFiscalVM.FaturaSerie;
            notaFiscal.FaturaNumero = notaFiscalVM.FaturaNumero;
            notaFiscal.MensagemFisco = notaFiscalVM.MensagemFisco == null ? "" : notaFiscalVM.MensagemFisco;
            notaFiscal.FaturaNumero = notaFiscal.FaturaNumero == null ? 0 : notaFiscal.FaturaNumero;
            notaFiscal.FaturaSerie = notaFiscal.FaturaSerie == null ? "0" : notaFiscal.FaturaSerie;
            notaFiscal.NumeroTelefone = notaFiscal.NumeroTelefone == null ? "" : notaFiscal.NumeroTelefone;
            notaFiscal.UserName = notaFiscalVM.UserName;
            notaFiscal.Observacoes = notaFiscalVM.Observacoes == null ? "" : notaFiscalVM.Observacoes;
            notaFiscal.Vencimento = notaFiscalVM.Vencimento == null ? "" : notaFiscalVM.Vencimento;
            return notaFiscal;
        }

Views/Shared/_Sidebar.cshtml
@{
    var paginaSelecionada = @ViewData["PaginaSelecionada"];
    var DireitoUsuario = @ViewData["DireitoUsuario"];
}

<ul class="nav nav-pills flex-column mb-auto">

    @if (paginaSelecionada == "Home")
    {
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" asp-area="" asp-controller="Home" asp-action="Index">

                <img class="bi pe-none me-2" width="16" height="16" src="~/images/home.png" />
               
                Home
            </a>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link" aria-current="page" asp-area="" asp-controller="Home" asp-action="Index">
                <img class="bi pe-none me-2" width="16" height="16" src="~/images/home.png" />
                Home
            </a>
        </li>
    }



    @if (paginaSelecionada == "Bancos")
    {
        <li>
            <a class="nav-link active " asp-controller="Bancos" asp-action="Index">
                <img class="bi pe-none me-2" width="16" height="16" src="~/images/logobank.png"  />
                
                
                Bancos
            </a>
        </li>
    }
    else
    {
        <li>
            <a class="nav-link " asp-controller="Bancos" asp-action="Index">
                <img class="bi pe-none me-2" width="16" height="16" src="~/images/logobank.png"  />
                Bancos
            </a>
        </li>
    }

    @if (paginaSelecionada == "Empresas")
    {
        <li>
            <a class="nav-link active " asp-controller="Empresas" asp-action="Index">
                <img class="bi pe-none me-2" width="16" height="16" src="~/images/company.png" />
                Empresas
            </a>
        </li>
    }
    else
    {
        <li>
            <a class="nav-link" asp-controller="Empresas" asp-action="Index">
                <img class="bi pe-none me-2" width="16" height="16" src="~/images/company.png" />
                Empresas
            </a>
        </li>
    }

    @if (paginaSelecionada == "NotaFiscal")
    {
        <li>
            <a class="nav-link active" asp-controller="NotaFiscals" asp-action="Index">

                <img class="bi pe-none me-2" width="16" height="16" src="~/images/invoice.png" />

                Notas Fiscais
            </a>
        </li>
    }
    else
    {
        <li>
            <a class="nav-link " asp-controller="NotaFiscals" asp-action="Index">
                <img class="bi pe-none me-2" width="16" height="16" src="~/images/invoice.png" />
                Notas Fiscais
            </a>
        </li>
    }
    @if(Convert.ToString(DireitoUsuario) == "Admin")
    {
        @if (paginaSelecionada == "Usuarios")
        {
            <li>
                <a class="nav-link active " asp-controller="Usuarios" asp-action="Index">
                    <img class="bi pe-none me-2" width="16" height="16" src="~/images/users.png" />

                    Usuários
                </a>
            </li>
        }
        else
        {
            <li>
                <a class="nav-link " asp-controller="Usuarios" asp-action="Index">
                    <img class="bi pe-none me-2" width="16" height="16" src="~/images/users.png" />
                    Usuários
                </a>
            </li>
        }   
    }



</ul>

Views/Shared/_SidebarCollapse.cshtml
<div class="d-flex flex-column flex-shrink-0 bg-body-tertiary" style="width: 4.5rem;">
    <a href="/" class="d-block p-3 link-body-emphasis text-decoration-none" title="Icon-only" data-bs-toggle="tooltip" data-bs-placement="right">
        <!-- <svg class="bi pe-none" width="40" height="32"><use xlink:href="#bootstrap" /></svg> -->
        <img width="40" height="32" src="~/images/favicon-32x32.png" />
        <span class="visually-hidden">Icon-only</span>
    </a>
    
    <ul class="nav nav-pills nav-flush flex-column mb-auto text-center">
        <li class="nav-item">
            <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link active py-3 border-bottom rounded-0" aria-current="page" title="Home" data-bs-toggle="tooltip" data-bs-placement="right">
                <svg class="bi pe-none" width="24" height="24" role="img" aria-label="Home"><use xlink:href="#home" /></svg>
            </a>
        </li>
        <li>
            <a asp-controller="Bancos" asp-action="Index" class="nav-link py-3 border-bottom rounded-0" title="Dashboard" data-bs-toggle="tooltip" data-bs-placement="right">
                <svg class="bi pe-none" width="24" height="24" role="img" aria-label="Dashboard"><use xlink:href="#speedometer2" /></svg>
            </a>
        </li>
        <li>
            <a asp-controller="Empresas" asp-action="Index" class="nav-link py-3 border-bottom rounded-0" title="Orders" data-bs-toggle="tooltip" data-bs-placement="right">
                <svg class="bi pe-none" width="24" height="24" role="img" aria-label="Orders"><use xlink:href="#table" /></svg>
            </a>
        </li>
        <li>
            <a asp-controller="NotaFiscals" asp-action="Index" class="nav-link py-3 border-bottom rounded-0" title="Products" data-bs-toggle="tooltip" data-bs-placement="right">
                <svg class="bi pe-none" width="24" height="24" role="img" aria-label="Products"><use xlink:href="#grid" /></svg>
            </a>
        </li>
        <li>
            <a asp-controller="Usuarios" asp-action="Index" class="nav-link py-3 border-bottom rounded-0" title="Customers" data-bs-toggle="tooltip" data-bs-placement="right">
                <svg class="bi pe-none" width="24" height="24" role="img" aria-label="Customers"><use xlink:href="#people-circle" /></svg>
            </a>
        </li>
    </ul>
   
</div>